local config = RAS.Config
config.Language = {}
local langconfig = config.Language
langconfig["English"] = {}

langconfig["English"]["Yes"] = "Yes"
langconfig["English"]["No"] = "No"
langconfig["English"]["Close"] = "Close"
langconfig["English"]["Comfirm"] = "Comfirm"
langconfig["English"]["NotificationTitle"] = "RAS Notification"
langconfig["English"]["ChatBannedResp"] = "Your message was not sent because you are banned from chatting"
langconfig["English"]["ChatSpamResp"] = "Your message was not sent because you are on a cooldown for {RAS_Cooldown} second(s)"
langconfig["English"]["PropBannedResp"] = "Sorry, you are banned from spawning props"
langconfig["English"]["PropSpamResp"] = "You cannot spawn props because you are on a cooldown for {RAS_Cooldown} second(s)"
langconfig["English"]["SentBannedResp"] = "Sorry, you are banned from spawning scripted entities"
langconfig["English"]["SentSpamResp"] = "You cannot spawn scripted entities because you are on a cooldown for {RAS_Cooldown} second(s)"
langconfig["English"]["RagdollBannedResp"] = "Sorry, you are banned from spawning ragdolls"
langconfig["English"]["RagdollSpamResp"] = "You cannot spawn ragdolls because you are on a cooldown for {RAS_Cooldown} second(s)"
langconfig["English"]["VehicleBannedResp"] = "Sorry, you are banned from spawning vehicles"
langconfig["English"]["VehicleSpamResp"] = "You cannot spawn vehicles because you are on a cooldown for {RAS_Cooldown} second(s)"
langconfig["English"]["NpcBannedResp"] = "Sorry, you are banned from spawning NPCs"
langconfig["English"]["NpcSpamResp"] = "You cannot spawn vehicles because you are on a cooldown for {RAS_Cooldown} second(s)"
langconfig["English"]["PlayerBanned"] = "{RAS_Player} was successfully banned from {RAS_Type}s"
langconfig["English"]["PlayerUnBanned"] = "{RAS_Player} was successfully unbanned from {RAS_Type}s"